//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Build.MSBuild.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Build.MSBuild.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;fileversion.h&quot;
        ///
        ///// If this is a debug build, set the file flag for debug.
        ///#ifndef ISDEBUG
        ///#define VER_DEBUG 0
        ///#else
        ///#define VER_DEBUG VS_FF_DEBUG
        ///#endif
        ///
        ///#ifndef ISPRERELEASE
        ///#define VER_PRERELEASE 0
        ///#else
        ///#define VER_PRERELEASE VS_FF_PRERELEASE
        ///#endif
        ///
        ///#ifndef PRIVATEBUILDSTRING
        ///#define VER_PRIVATEBUILD 0
        ///#else
        ///#define VER_PRIVATEBUILD VS_FF_PRIVATEBUILD
        ///#endif
        ///
        ///#ifndef SPECIALBUILDSTRING
        ///#define VER_SPECIALBUILD 0
        ///#else
        ///#define VER_SPECIALBUILD VS_FF_SPECIALBUILD
        ///#endif        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileVersionInfo {
            get {
                return ResourceManager.GetString("FileVersionInfo", resourceCulture);
            }
        }
    }
}
